// <auto-generated />
using System;
using AgroConecta.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroConecta.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516054002_CriarTabelaCulturas")]
    partial class CriarTabelaCulturas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroConecta.Models.AnaliseCultura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CulturaId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recomendacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CulturaId");

                    b.ToTable("AnalisesCulturas");
                });

            modelBuilder.Entity("AgroConecta.Models.AtividadeAgricola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CulturaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CulturaId");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("AtividadesAgricolas");
                });

            modelBuilder.Entity("AgroConecta.Models.Cultura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AreaPlantio")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataIrrigacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPlantio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrevistaColheita")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeCultura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("Culturas");
                });

            modelBuilder.Entity("AgroConecta.Models.Propriedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Cib")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CriadoPor")
                        .HasColumnType("int");

                    b.Property<string>("LocalizacaoGeo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Propriedades");
                });

            modelBuilder.Entity("AgroConecta.Models.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagemPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("int");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("AgroConecta.Models.AnaliseCultura", b =>
                {
                    b.HasOne("AgroConecta.Models.Cultura", "Cultura")
                        .WithMany()
                        .HasForeignKey("CulturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cultura");
                });

            modelBuilder.Entity("AgroConecta.Models.AtividadeAgricola", b =>
                {
                    b.HasOne("AgroConecta.Models.Cultura", "Cultura")
                        .WithMany()
                        .HasForeignKey("CulturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroConecta.Models.Propriedade", "Propriedade")
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cultura");

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroConecta.Models.Cultura", b =>
                {
                    b.HasOne("AgroConecta.Models.Propriedade", "Propriedade")
                        .WithMany("Culturas")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroConecta.Models.Relatorio", b =>
                {
                    b.HasOne("AgroConecta.Models.Propriedade", "Propriedade")
                        .WithMany("Relatorios")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroConecta.Models.Propriedade", b =>
                {
                    b.Navigation("Culturas");

                    b.Navigation("Relatorios");
                });
#pragma warning restore 612, 618
        }
    }
}
